Add Live Activity type to EPushType
sideshow/apns2 pull request #214
Opened 2022-10-20 17:24 UTC by CommanderNULL

Live Activities is a new feature in iOS 16 that helps users stay on top of things that are happening in real-time. This library can be used to trigger them and it just needs new const for convenience.

2022-11-02 21:29 UTC, nijanthanh approved these changes

2022-11-02 21:35 UTC, nijanthanh commented
@sideshow could you please review this?

2022-12-13 07:18 UTC, ozamanav requested changes
Don't we require few changes in payload/builder.go
[https://github.com/sideshow/apns2/blob/master/payload/builder.go#L32](https://github.com/sideshow/apns2/blob/master/payload/builder.go#L32)

like to add content-state, dismissal-date, event, etc..

2022-12-19 07:53 UTC, ozamanav commented
@CommanderNULL 
I've raised another PR with all required changes 
Please take a look and let me know

https://github.com/sideshow/apns2/pull/217

2024-08-08 09:04 UTC, closed without merging